---

- name: Updates repositories cache
  hosts: all
  become: true
  roles:
    - base

- name: Webserver play
  hosts: webServer
  become: true
  roles:
    - webServer


- name: Database play
  hosts: databaseServer
  become: true
  roles:
    - databaseServer


- name: File server play
  hosts: fileServer    
  become: true
  roles:
    - fileServer