---

- name: Updates repositories cache
  hosts: all
  become: true
  roles:
    - base

- hosts: webServer
  become: true
  roles:
    - webServer

- hosts: databaseServer
  become: true
  roles:
    - databaseServer

- hosts: fileServer    
  become: true
  roles:
    - fileServer