- name: updates (Centos)
  tags: always
  dnf:
    update_cache: yes  
  when: ansible_facts['distribution'] == "CentOS"


- name: updates (Ubuntu)
  tags: always
  apt:
    update_cache: yes  
  when: ansible_distribution == 'Ubuntu'